version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: node-app-c1
    volumes:
    - ./src:/node-app/src:ro
    ports:
    - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MODE_ENV=development
    command: npm run watch
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
volumes:
  mongo-db: