version: "3"
services:
  node-app:
    image: khalilmaihoub/test1
    #container_name: node-app-c
    env_file:
     - ./.env
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - node-app

