version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: node-app-c2
    ports:
    - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MODE_ENV=production
    command: npm run start
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongo-db:
